### ISSUE TITLE
Documentation Checklist

### ISSUE THREAD

**Issue by AE637** [CSUN-SeniorDesign/eat-infrastructure#60]
Please check off your task when your documentation is completed, review what you did in case I missed something here

- [x] IAM (users, groups, policies, etc)

- [x] VPC (subnets)

- [x] VPC (route tables)

- [x] VPC( Internet Gateways)

- [x] VPC (NAT/Bastion instance)

- [x] Service infrastructure (Blog Servers)

- [x] Service infrastructure (Elastic IP)

- [x] Service infrastructure (EC2 security groups)

- [x] Service infrastructure (Application Load Balancers (ALB))

- [x] Service infrastructure (Route53)

- [x] Service infrastructure (user keys on the instances, etc)

- [x] State and Locking

- [x] Ansible (Web server setup and configuration)

- [x] Ansible (Service deployment)

**Comment by h1ddengames** [comment]
Good work
